### ISSUE TITLE
Dietpi 404

### ISSUE THREAD

**Issue by numbermonkey** [tbblake/myScripts#2]
Sorry, feel like a complete dummy.  I'm a tinkerer enthusiast :) 
Tried this on my 2nd pi running Bullseye. Worked like a charm. I did need to sudo the CP commands and the systemctl needed password authentication. But it worked and I get /dhcpLeases.php output. Yay.
But it's not the DHCP server that answers fastest so it has very few of my LAN clients. I tried this on my 1st pi running Dietpi. First problem was
[dietpi@pi2
~]$ systemctl restart lighttpd
Failed to connect to bus: No such file or directory
[dietpi@pi2
~]$
hmm.
so i just rebooted :)
BUT http://<IP>/dchpLeases.php returns a 404 although can see that php file 
[dietpi@pi2
~]$ locate dhcpLeases.php
/home/dietpi/gits/myScripts/dhcpPihole/dhcpLeases.php
/var/www/html/dhcpLeases.php
[dietpi@pi2
~]$
I dont understand.
Also:
[dietpi@pi2
~]$ sudo service lighttpd status
● lighttpd.service - Lighttpd Daemon
     Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/lighttpd.service.d
             └─dietpi.conf
     Active: active (running) since Tue 2023-04-18 16:23:18 BST; 13min ago
    Process: 388 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
   Main PID: 450 (lighttpd)
      Tasks: 1 (limit: 990)
        CPU: 9.705s
     CGroup: /system.slice/lighttpd.service
             └─450 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf

Apr 18 16:23:01 pi2 systemd[1]: Starting Lighttpd Daemon...
Apr 18 16:23:18 pi2 lighttpd[388]: 2023-04-18 16:23:01: configfile.c.1142) WARNING: unknown config-key: accesslog.filename (ignored)
Apr 18 16:23:18 pi2 lighttpd[388]: 2023-04-18 16:23:01: configfile.c.1142) WARNING: unknown config-key: accesslog.filename (ignored)
Apr 18 16:23:18 pi2 lighttpd[388]: 2023-04-18 16:23:01: configfile.c.1142) WARNING: unknown config-key: accesslog.filename (ignored)
Apr 18 16:23:18 pi2 lighttpd[388]: 2023-04-18 16:23:01: configfile.c.1142) WARNING: unknown config-key: accesslog.filename (ignored)
Apr 18 16:23:18 pi2 lighttpd[388]: 2023-04-18 16:23:01: configfile.c.1142) WARNING: unknown config-key: accesslog.filename (ignored)
Apr 18 16:23:18 pi2 lighttpd[388]: 2023-04-18 16:23:01: configfile.c.1142) WARNING: unknown config-key: accesslog.filename (ignored)
Apr 18 16:23:18 pi2 systemd[1]: Started Lighttpd Daemon.
[dietpi@pi2
~]$
Help a ignorant newb out?

**Comment by tbblake** [comment]
You say you tried:

http:///dchpLeases.php

Where it should be http://192.168.50.50/dhcpLeases.php

BUT replace 192.168.50.50 with the IP of your dietpi install.  Also, you have it spelled dchpLeases.php, note the c and the h are transposed.

If you have those right, take a look at the lighttpd error log, it's in /var/log/lighttpd/error-pihole.log

**Comment by tbblake** [comment]
Also updated the readme to include sudo, thanks for the catch.  I'm old enough that I still use root for everything (I know, I know....)

**Comment by numbermonkey** [comment]
> You say you tried:
> 
> http:///dchpLeases.php
> 
> Where it should be http://192.168.50.50/dhcpLeases.php
> 
> BUT replace 192.168.50.50 with the IP of your dietpi install. Also, you have it spelled dchpLeases.php, note the c and the h are transposed.
> 
> If you have those right, take a look at the lighttpd error log, it's in /var/log/lighttpd/error-pihole.log

I did have the IP in the URL - I just managed to edit it out when I posted :D I'll take a look at the error log.

**Comment by tbblake** [comment]
Curious, did you get it working?

**Comment by numbermonkey** [comment]
> Curious, did you get it working?

Sorry, got busy with work and life stuff. I think it's related to accesslog. That module doesn't seem to be part of the DietPi lighttpd install. I'll dig into it this weekend.

**Comment by tbblake** [comment]
I was curious so I loaded dietpi into a vm and used it's menus to install pihole and yup, no access.log configuration at all, which makes sense for dietpi.  I bet if you remove the /etc/lighttpd/conf-enabled/10-accesslog-dhcpLeases.conf file it'll start working for you.

**Comment by numbermonkey** [comment]
Thank you.
